name: nearmiss-mlops-demo
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas>=2.1
      - numpy>=1.26
      - scikit-learn>=1.3
      - lightgbm>=4.0
      - mlflow>=2.13
      - pyspark>=3.4
      - delta-spark>=3.2.0
      - pyarrow>=14.0
